spring.application.name=task16-ApiGateway
server.port=8083
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.cloud.gateway.routes[0].id=task16-user-service
spring.cloud.gateway.routes[0].uri=lb://task16-UserService
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**